[package]
name = "rtop"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.4", features = ["macros", "ws"]}
serde_json = "1.0.140"
sysinfo = "0.35.2"
tokio = { version = "1.45.1", features = ["full"] }
